# Generated by Django 4.2.16 on 2025-08-11 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammember',
            name='specialty',
            field=models.CharField(blank=True, choices=[('Cabelereira', 'Cabelereira'), ('Manicure', 'Manicure'), ('Esteticista', 'Esteticista'), ('Barbeiro', 'Barbeiro')], max_length=100),
        ),
    ]
