# Generated by Django 4.2.16 on 2025-08-13 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0002_alter_teammember_specialty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammember',
            name='specialty',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
